### PR TITLE
Update sql-server-linux-deploy-pacemaker-cluster.md

### PR DESCRIPTION
**Pull request by t-deman**
Temporary update (Page not finished)

### CODE REVIEW

**Comment by t-deman** [comment]
This is a partial update of the doc.

**Comment by t-deman** [comment]
Sorry for the close!

**Comment by v-elcou** [comment]
Hello, @t-deman, 
Thank for your contribution. We are currently reviewing and will communicate the decision taken. 
Thanks for your time and support on this.

Kind regards,
Microsoft C&E Localization Team

**Comment by LisandroSu** [comment]
Hello, @t-deman 

Thank you for your feedback and suggestion. 
 
The feedback has been partially accepted.. We will adjust  your feedback in order to comply with Microsoft Style Guide. We will release this article in the next localization release round accordingly.

Many thanks for your time and  support on this. 
 
Microsoft C&E Localization Team

**Pull request merged**
