### PR TITLE
Update sql-server-linux-overview.md

### PR DESCRIPTION
**Pull request by agriffard**
Fix Title and links.

### CODE REVIEW

**Comment by gosali** [comment]
Hi @agriffard , we are still in discussing, will update the decision later soon. 

In the meantime, Could you please sign the CLA license?
  
Thanks for your support,
Microsoft C&E Localization Team

**Comment by agriffard** [comment]
OK, but right now there is no link to sign the CLA, just a line saying : license/cla  — Waiting for status to be reported

**Comment by agriffard** [comment]
I managed to sign it after submitting another PR.

**Comment by gosali** [comment]
@agriffard , Thank you for your feedback and suggestion! 
  
The suggestion will be merged to the production, we will re-release this articles in the next loc release round. 

We will check  the "CLA Sign in" issue.  

Microsoft C&E Localization Team

**Pull request merged**
